# Site settings
title: CISSP Mindset
email: contact@cissp.dennisleehappy.org
description: >- # this means to ignore newlines until "baseurl:"
  CISSP Mindset - 專業的 CISSP 和 CCSP 認證學習資源平台，提供完整的學習指南、模擬試題和實戰案例分析
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # 留空以使用 GitHub Pages 的預設 URL
twitter_username: cisspmindset
github_username: twister5-com-tw-dev-dep
author: CISSP Mindset Team

# SEO 設定
lang: zh-TW
timezone: Asia/Taipei
google_analytics: # 添加您的 Google Analytics ID
google_analytics_anonymize_ip: true

# 社交媒體設定
social:
  name: CISSP Mindset
  links:
    - https://github.com/twister5-com-tw-dev-dep
    - https://twitter.com/cisspmindset

# Build settings
markdown: kramdown
theme: minima

# Exclude files and directories to avoid conflicts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .github
  - scripts
  - package.json
  - package-lock.json
  - .DS_Store
  - README.md
  - DEPLOYMENT.md

# Collections
collections:
  ccsp:
    output: true
    permalink: /ccsp/:name/
  domain3:
    output: true
    permalink: /domain3/:name/
  domain5:
    output: true
    permalink: /domain5/:name/

# 預設設定
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "CISSP Mindset Team"
  - scope:
      path: ""
      type: "ccsp"
    values:
      layout: "page"
      author: "CISSP Mindset Team"
  - scope:
      path: ""
      type: "domain3"
    values:
      layout: "page"
      author: "CISSP Mindset Team"
  - scope:
      path: ""
      type: "domain5"
    values:
      layout: "page"
      author: "CISSP Mindset Team"
