# Site settings
title: CISSP Mindset
email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  CISSP Mindset - Comprehensive study materials and resources for CISSP certification
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache

# Exclude files and directories to avoid conflicts
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .github
  - scripts
  - package.json
  - package-lock.json
  - .DS_Store
  - Domain3
  - Domain5
  - CCSP
  - interview
  - "*.md"
  - "*.html"

# Include only necessary directories
include:
  - _layouts
  - _posts
  - _pages
  - _ccsp
  - _domain3
  - _domain5
  - assets
  - index.html

# Collections
collections:
  ccsp:
    output: true
    permalink: /ccsp/:name/
  domain3:
    output: true
    permalink: /domain3/:name/
  domain5:
    output: true
    permalink: /domain5/:name/

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-category
    tag: archive-tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
